### PR TITLE
Add Bytedance IconPack with 10,632 Icons (2658 unique icons in 4 weights)

### PR DESCRIPTION
**Pull request by leewyatt**
Hello,

I've added the Bytedance IconPack (https://github.com/bytedance/iconpark) to the project. This IconPack contains a total of 2,658 unique icons, each available in 4 different weights, leading to a grand total of 10,632 icons.

**Details**:
- Source: [Bytedance IconPack](https://github.com/bytedance/iconpark)
- Unique Icons: 2,658
- Total Icons (considering 4 weights): 10,632

This PR targets the `master` branch. I'm not sure if there's a need for modifications with respect to the `java1.8` branch, so please let me know if such changes are required.

If there are any concerns or if further communication is needed, please don't hesitate to contact me.

Thank you for considering this contribution.

Best regards,
Lee Wyatt

### CODE REVIEW

**Comment by leewyatt** [comment]
image
image

**Comment by leewyatt** [comment]
image
The copyright information for the Handler and Provider classes was copied from another piece of code. I'm uncertain if this approach is appropriate.

**Comment by aalmiray** [comment]
Thank you for this amazing contribution. But before I can merge it, do you know what license governs these icons? We can only use icons whose license allow free redistribution.

**Comment by leewyatt** [comment]
These SVG icons are sourced from an open-source project called [Bytedance IconPack](https://github.com/bytedance/iconpark), which is under the Apache-2.0 license. However, the SVG icons couldn't be directly converted to font files. I wrote a script to process these SVGs, and then used the online tool at https://icomoon.io/ to convert the processed SVGs into font files. I plan to open-source the processed SVGs soon.
You might also want to review these sites:

1. https://iconpark.oceanengine.com/home
2. https://iconpark.oceanengine.com/official
3. https://github.com/bytedance/iconpark

image

**Pull request merged**
